Repository Trading-Trends/Trading-Trends, pull requests merged in 2024-10, with the labels that each got.

#9 feat: 업비트 실시간 데이터를 카프카로 전송
  coin/build.gradle
  coin/src/main/java/com/tradingtrends/coin/infrastructure/CoinTopic.java
  coin/src/main/java/com/tradingtrends/coin/infrastructure/config/AppConfig.java
  coin/src/main/java/com/tradingtrends/coin/infrastructure/messaging/UpbitWebSocketService.java
  coin/src/main/resources/application.yml
  docker-compose.yml
Labels: feat, chore

#12 feat: upbit-data 토픽을 구독하는 handleCoinEvent 메서드 구현
  coin/src/main/java/com/tradingtrends/coin/infrastructure/messaging/UpbitWebSocketService.java
  market/src/main/java/com/tradingtrends/market/MarketApplication.java
  market/src/main/java/com/tradingtrends/market/infrastructure/messaging/MarketDataConsumer.java
  market/src/test/java/com/tradingtrends/market/MarketApplicationTests.java
Labels: feat

#13 Feature/corpinfo batch
  batch/build.gradle
  batch/src/main/java/com/tradingtrends/batch/BatchApplication.java
  batch/src/main/java/com/tradingtrends/batch/application/dto/CorporateCodesResponseDto.java
  batch/src/main/java/com/tradingtrends/batch/application/dto/DartCorporateFinanceApiResponse.java
  batch/src/main/java/com/tradingtrends/batch/application/service/CorporateService.java
  batch/src/main/java/com/tradingtrends/batch/domain/model/CorporateCodes.java
  batch/src/main/java/com/tradingtrends/batch/domain/model/CorporateFinance.java
  batch/src/main/java/com/tradingtrends/batch/domain/repository/CorporateFinanceRepository.java
  batch/src/main/java/com/tradingtrends/batch/domain/repository/CorporatesCodesRepository.java
  batch/src/main/java/com/tradingtrends/batch/infrastructure/config/DartCorporateApiBatchConfig.java
  batch/src/main/java/com/tradingtrends/batch/infrastructure/config/ElasticsearchConfig.java
  batch/src/main/java/com/tradingtrends/batch/infrastructure/config/RestTemplateConfig.java
  batch/src/main/java/com/tradingtrends/batch/infrastructure/tasklet/RepeatScheduleTasklet.java
  batch/src/main/java/com/tradingtrends/batch/infrastructure/trigger/DartCorporateApiJobScheduler.java
  batch/src/main/java/com/tradingtrends/batch/presentation/controller/CorporateController.java
  batch/src/main/resources/application.yml
Labels: fix, feat

#14 Feature/websocket kafka
  .gitignore
  coin/build.gradle
  coin/src/main/java/com/tradingtrends/coin/application/service/KafkaCleanUpService.java
  coin/src/main/java/com/tradingtrends/coin/infrastructure/messaging/UpbitWebSocketService.java
  coin/src/main/java/com/tradingtrends/coin/presentation/controller/WebsocketController.java
  coin/src/main/resources/application.yml
  docker-compose.yml
  market/src/main/java/com/tradingtrends/market/infrastructure/messaging/MarketDataConsumer.java
Labels: fix, refactor

#15 Feature/websocket kafka
  coin/src/main/java/com/tradingtrends/coin/application/service/KafkaCleanUpService.java
  coin/src/main/java/com/tradingtrends/coin/infrastructure/config/KafkaProducerConfig.java
  coin/src/main/java/com/tradingtrends/coin/infrastructure/config/KafkaTopicConfig.java
  coin/src/main/java/com/tradingtrends/coin/infrastructure/messaging/UpbitWebSocketService.java
  coin/src/main/resources/application.yml
  docker-compose.yml
  market/src/main/java/com/tradingtrends/market/infrastructure/config/KafkaConsumerConfig.java
  market/src/main/resources/application.yml
Labels: feat, refactor

#16 feat: Redis 설정 및 컨슈밍한 데이터를 Redis에 캐싱
  docs/client/config/http-client.env.json
  docs/client/market.http
  market/src/main/java/com/tradingtrends/market/infrastructure/config/RedisConfig.java
  market/src/main/java/com/tradingtrends/market/infrastructure/messaging/MarketDataConsumer.java
Labels: feat, chore

#17 feat: Dart API to Elastic 기능 구현 및 batch 환경설정 재구성
  batch/build.gradle
  batch/docker-compose.yml
  batch/src/main/java/com/tradingtrends/batch/application/scheduler/DisclosureScheduler.java
  batch/src/main/java/com/tradingtrends/batch/application/service/DartDisclosureService.java
  batch/src/main/java/com/tradingtrends/batch/application/service/DartToElasticsearchService.java
  batch/src/main/java/com/tradingtrends/batch/domain/model/Entity/Disclosure.java
  batch/src/main/java/com/tradingtrends/batch/domain/model/Entity/DisclosureDocument.java
  batch/src/main/java/com/tradingtrends/batch/domain/repository/DisclosureRepository.java
  batch/src/main/java/com/tradingtrends/batch/infrastructure/config/BatchConfig.java
  batch/src/main/java/com/tradingtrends/batch/infrastructure/config/DartCorporateApiBatchConfig.java
  batch/src/main/java/com/tradingtrends/batch/infrastructure/trigger/DartCorporateApiJobScheduler.java
  batch/src/main/java/com/tradingtrends/batch/presentation/controller/DartManualController.java
  batch/src/main/resources/application.yml
  corporate/build.gradle
Labels: feat, refactor

#19 feat: ElasticSearch로 공시 자료 보고서 rawData(xml) 포함 기본 정보 적재
  batch/src/main/java/com/tradingtrends/batch/application/service/DartToElasticsearchService.java
  batch/src/main/java/com/tradingtrends/batch/domain/model/Entity/DisclosureDocument.java
  batch/src/main/java/com/tradingtrends/batch/infrastructure/config/BatchConfig.java
  batch/src/main/java/com/tradingtrends/batch/presentation/controller/DartManualController.java
  corporate/build.gradle
  corporate/src/main/java/com/tradingtrends/corporate/CorporateApplication.java
  corporate/src/main/java/com/tradingtrends/corporate/application/dto/CorporateMajorFinanceResponseDto.java
  corporate/src/main/java/com/tradingtrends/corporate/application/dto/CorporateMajorFinanceSearchRequestDto.java
  corporate/src/main/java/com/tradingtrends/corporate/application/service/CorporateMajorFinanceService.java
  corporate/src/main/java/com/tradingtrends/corporate/domain/model/entity/CorporateMajorFinance.java
  corporate/src/main/java/com/tradingtrends/corporate/domain/repository/CorporateMajorFinanceRepository.java
  corporate/src/main/java/com/tradingtrends/corporate/domain/specification/CorporateMajorFinanceSpecification.java
  corporate/src/main/java/com/tradingtrends/corporate/presentation/controller/CorporateMajorFinanceController.java
  corporate/src/main/resources/application.yml
  init.sql
Labels: fix, feat, refactor

#20 feat: 한국투자증권 실시간 데이터 kafka 적재
  .gitignore
  docker-compose.yml
  docs/client/config/http-client.env.json
  docs/client/market.http
  stock/build.gradle
  stock/src/main/java/com/tradingtrends/stock/StockApplication.java
  stock/src/main/java/com/tradingtrends/stock/application/dto/ApprovalRequest.java
  stock/src/main/java/com/tradingtrends/stock/application/service/StockWebSocketKeyService.java
  stock/src/main/java/com/tradingtrends/stock/infrastructure/StockTopic.java
  stock/src/main/java/com/tradingtrends/stock/infrastructure/config/AppConfig.java
  stock/src/main/java/com/tradingtrends/stock/infrastructure/config/KafkaProducerConfig.java
  stock/src/main/java/com/tradingtrends/stock/infrastructure/config/KafkaTopicConfig.java
  stock/src/main/java/com/tradingtrends/stock/infrastructure/messaging/StockWebSocketService.java
  stock/src/main/java/com/tradingtrends/stock/presentation/controller/WebsocketController.java
  stock/src/main/resources/application.yml
Labels: docs, feat, chore

#21 Feature/redis pub sub
  docker-compose.yml
  market/src/main/java/com/tradingtrends/market/infrastructure/config/RedisConfig.java
  market/src/main/resources/application.yml
  redis_sentinel/sentinel1.conf
  redis_sentinel/sentinel2.conf
  redis_sentinel/sentinel3.conf
Labels: refactor, chore

#22 feat: Stock 서버 종료 시 토픽 삭제
  stock/src/main/java/com/tradingtrends/stock/application/service/KafkaCleanUpService.java
Labels: feat

#23 feat: 코스피100 종목으로 카프카 적재 및 컨슈머 구현
  docs/client/market.http
  market/src/main/java/com/tradingtrends/market/infrastructure/messaging/MarketDataConsumer.java
  market/src/main/resources/application.yml
  stock/src/main/java/com/tradingtrends/stock/application/dto/ApprovalRequest.java
  stock/src/main/java/com/tradingtrends/stock/infrastructure/messaging/StockWebSocketService.java
Labels: docs, feat

#25 Feature/coin search api
  coin/src/main/java/com/tradingtrends/coin/CoinApplication.java
  coin/src/main/java/com/tradingtrends/coin/application/dto/CoinApiResponseDto.java
  coin/src/main/java/com/tradingtrends/coin/application/dto/CoinApiSnapshotResponseDto.java
  coin/src/main/java/com/tradingtrends/coin/application/dto/CoinWatchlistResponseDto.java
  coin/src/main/java/com/tradingtrends/coin/application/service/CoinApiService.java
  coin/src/main/java/com/tradingtrends/coin/application/service/CoinWatchlistService.java
  coin/src/main/java/com/tradingtrends/coin/application/service/KafkaCleanUpService.java
  coin/src/main/java/com/tradingtrends/coin/domain/model/CoinInfo.java
  coin/src/main/java/com/tradingtrends/coin/domain/model/WatchlistCoin.java
  coin/src/main/java/com/tradingtrends/coin/domain/repository/CoinRepository.java
  coin/src/main/java/com/tradingtrends/coin/domain/repository/WatchlistCoinRepository.java
  coin/src/main/java/com/tradingtrends/coin/infrastructure/config/KafkaTopicConfig.java
  coin/src/main/java/com/tradingtrends/coin/infrastructure/config/RedisCacheConfig.java
  coin/src/main/java/com/tradingtrends/coin/infrastructure/config/RedisConfig.java
  coin/src/main/java/com/tradingtrends/coin/infrastructure/messaging/CoinTopic.java
  coin/src/main/java/com/tradingtrends/coin/infrastructure/messaging/UpbitWebSocketService.java
  coin/src/main/java/com/tradingtrends/coin/presentation/controller/CoinApiController.java
  coin/src/main/java/com/tradingtrends/coin/presentation/controller/CoinWatchlistController.java
  coin/src/main/java/com/tradingtrends/coin/presentation/request/CoinWatchlistRequest.java
  coin/src/main/resources/application.yml
  coin/src/test/java/com/tradingtrends/coin/CoinInfoApplicationTests.java
  market/build.gradle
  market/src/main/java/com/tradingtrends/market/application/service/RedisSubscriberListener.java
  market/src/main/java/com/tradingtrends/market/application/service/WebSocketService.java
  market/src/main/java/com/tradingtrends/market/infrastructure/config/WebSocketConfig.java
  market/src/main/java/com/tradingtrends/market/infrastructure/handler/CustomWebSocketHandler.java
  market/src/main/java/com/tradingtrends/market/infrastructure/messaging/MarketDataConsumer.java
Labels: feat, refactor, chore

#28 fix : Coin search api 에러 수정
  build.gradle
  coin/src/main/java/com/tradingtrends/coin/application/dto/CoinApiResponseDto.java
  coin/src/main/java/com/tradingtrends/coin/application/dto/CoinApiSnapshotResponseDto.java
  coin/src/main/java/com/tradingtrends/coin/application/service/CoinApiService.java
  coin/src/main/java/com/tradingtrends/coin/domain/model/CoinInfo.java
  coin/src/main/java/com/tradingtrends/coin/presentation/controller/CoinApiController.java
  coin/src/main/java/com/tradingtrends/coin/presentation/controller/CoinWatchlistController.java
Labels: fix, refactor

#30 feat: 주식 정보 조회 API 구현
  docs/client/market.http
  stock/src/main/java/com/tradingtrends/stock/application/dto/StockResponse.java
  stock/src/main/java/com/tradingtrends/stock/application/service/StockService.java
  stock/src/main/java/com/tradingtrends/stock/domain/repository/StockRepository.java
  stock/src/main/java/com/tradingtrends/stock/presentation/controller/StockController.java
Labels: feat

#32 feat: user api (회원수정, 탈퇴, 상세조회) 기능 추가 및 전체적인 코드 리팩토링
  auth/src/main/java/com/tradingtrends/auth/application/service/AuthService.java
  auth/src/main/java/com/tradingtrends/auth/application/service/TokenService.java
  auth/src/main/java/com/tradingtrends/auth/infrastructure/client/UserClient.java
  auth/src/main/java/com/tradingtrends/auth/infrastructure/client/UserDetailsDto.java
  auth/src/main/java/com/tradingtrends/auth/presentation/controller/AuthController.java
  auth/src/main/resources/application.yml
  batch/build.gradle
  batch/docker-compose.yml
  batch/src/main/java/com/tradingtrends/batch/application/service/CorporateService.java
  batch/src/main/java/com/tradingtrends/batch/domain/model/CorporateFinance.java
  batch/src/main/java/com/tradingtrends/batch/domain/repository/CorporateFinanceRepository.java
  batch/src/main/java/com/tradingtrends/batch/infrastructure/config/DartCorporateApiBatchConfig.java
  batch/src/main/java/com/tradingtrends/batch/infrastructure/config/ElasticsearchConfig.java
  batch/src/main/java/com/tradingtrends/batch/presentation/controller/CorporateController.java
  batch/src/main/resources/application.yml
  coin/src/main/java/com/tradingtrends/coin/infrastructure/messaging/UpbitWebSocketService.java
  common/build.gradle
  corporate/build.gradle
  corporate/src/main/java/com/tradingtrends/corporate/application/dto/DisclosureResponseDto.java
  corporate/src/main/java/com/tradingtrends/corporate/application/service/DisclosureSearchService.java
  corporate/src/main/java/com/tradingtrends/corporate/domain/model/DisclosureDocument.java
  corporate/src/main/java/com/tradingtrends/corporate/presentation/controller/DisclosureController.java
  docker-compose.yml
  docs/client/market.http
  gateway/src/main/java/com/tradingtrends/gateway/LocalJwtAuthenticationFilter.java
  gateway/src/main/java/com/tradingtrends/gateway/application/AuthService.java
  gateway/src/main/java/com/tradingtrends/gateway/infrastructure/AuthClient.java
  gateway/src/main/resources/application.yml
  market/src/main/java/com/tradingtrends/market/infrastructure/messaging/MarketDataConsumer.java
  user/src/main/java/com/tradingtrends/user/application/dto/UserDetailsDto.java
  user/src/main/java/com/tradingtrends/user/application/dto/UserResponseDto.java
  user/src/main/java/com/tradingtrends/user/application/service/UserService.java
  user/src/main/java/com/tradingtrends/user/domain/model/User.java
  user/src/main/java/com/tradingtrends/user/presentation/controller/UserController.java
  user/src/main/java/com/tradingtrends/user/presentation/controller/UserFeignController.java
  user/src/main/java/com/tradingtrends/user/presentation/request/DeleteRequestDto.java
  user/src/main/java/com/tradingtrends/user/presentation/request/UserRequestDto.java
  user/src/main/resources/application.yml
Labels: fix, feat, refactor, chore

#34 Feature/listener adapter
  coin/src/main/java/com/tradingtrends/coin/infrastructure/config/KafkaTopicConfig.java
  coin/src/main/java/com/tradingtrends/coin/presentation/controller/WebsocketController.java
  coin/src/main/resources/application.yml
  docker-compose.yml
  jmx-exporter-config.yml
  market/src/main/java/com/tradingtrends/market/application/service/ClientSubscriptionService.java
  market/src/main/java/com/tradingtrends/market/application/service/CoinRedisSubscriberListener.java
  market/src/main/java/com/tradingtrends/market/application/service/StockRedisSubscriberListener.java
  market/src/main/java/com/tradingtrends/market/infrastructure/config/RedisConfig.java
  market/src/main/java/com/tradingtrends/market/infrastructure/config/RedisListenerConfig.java
  market/src/main/java/com/tradingtrends/market/infrastructure/messaging/CoinMarketDataConsumer.java
  market/src/main/java/com/tradingtrends/market/infrastructure/messaging/MarketDataConsumer.java
  market/src/main/java/com/tradingtrends/market/infrastructure/messaging/StockMarketDataConsumer.java
  market/src/main/java/com/tradingtrends/market/infrastructure/util/CheckChannelInRedis.java
  market/src/main/resources/application.yml
  prometheus.yml
  stock/build.gradle
  stock/src/main/java/com/tradingtrends/stock/infrastructure/config/KafkaTopicConfig.java
  stock/src/main/java/com/tradingtrends/stock/infrastructure/messaging/StockWebSocketService.java
  stock/src/main/resources/application.yml
Labels: fix, feat, refactor

#44 feat: 주식 관심 종목 API 개발
  docs/client/stock.http
  stock/src/main/java/com/tradingtrends/stock/application/dto/StockWatchlistRequest.java
  stock/src/main/java/com/tradingtrends/stock/application/dto/StockWatchlistResponse.java
  stock/src/main/java/com/tradingtrends/stock/application/service/StockWatchlistService.java
  stock/src/main/java/com/tradingtrends/stock/domain/model/WatchlistStock.java
  stock/src/main/java/com/tradingtrends/stock/domain/repository/WatchlistStockRepository.java
  stock/src/main/java/com/tradingtrends/stock/presentation/controller/StockWatchlistController.java
Labels: feat

#45 Apache Kafka Monitoring 로직 구성
  docker-compose-kafka.yml
  grafana-storage/grafana.db
  jmx_exporter/jmx_exporter_config.yml
  jmx_exporter/jmx_prometheus_javaagent-1.0.1.jar
  prometheus.yml
Labels: fix, feat, refactor, comment

#46 refactor : logstash 실행 error 해결
  docker-compose-elk.yml
  docs/scenario/scenario-3-1.http
  eureka/src/main/resources/application.yml
  logstash/pipeline/logstash.conf
Labels: refactor

#51 feat: 클라이언트가 수신한 메시지에서 구독한 종목을 식별할 수 있도록 개선
  market/src/main/java/com/tradingtrends/market/application/service/WebSocketService.java
  market/src/main/java/com/tradingtrends/market/infrastructure/messaging/CoinMarketDataConsumer.java
  market/src/main/java/com/tradingtrends/market/infrastructure/messaging/StockMarketDataConsumer.java
Labels: feat

#52 feat: 각 module service ci.yml 작성
  .github/workflows/auth-ci.yml
  .github/workflows/coin-ci.yml
  .github/workflows/gateway-ci.yml
  .github/workflows/market-ci.yml
  .github/workflows/notification-ci.yml
  .github/workflows/stock-ci.yml
  .github/workflows/user-ci.yml
Labels: feat
